# Generated by Django 2.0 on 2017-12-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_title', models.CharField(max_length=50)),
                ('photo_file', models.ImageField(upload_to='images/')),
                ('photo_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
