# Generated by Django 2.0 on 2017-12-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(max_length=50)),
                ('main_content', models.TextField()),
                ('main_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
